checkpatch -strict fixes for upstream files
Xilinx/xoclv2 pull request #131
Opened 2021-01-27 17:20 UTC by houlz0507

2021-01-27 19:51 UTC, maxzhen requested changes
please update checkpatch arguments in lint.sh so that we won't make the same mistake in the future.

2021-01-27 19:51 UTC, maxzhen commented on src/drivers/fpga/xrt/lib/group.c
> +struct xrt_subdev_drvdata xrt_grp_data = {
static should not be removed.

2021-01-27 20:38 UTC, maxzhen approved these changes

2021-01-28 04:01 UTC, sonals approved these changes

2021-01-30 00:38 UTC, merged